/*
 * spoke_handler
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// Provider : Fields with value `\"simple\"` parse as `Kind::Simple`. Fields with value `\"fancy\"` parse as `Kind::SoFancy`.
/// Fields with value `\"simple\"` parse as `Kind::Simple`. Fields with value `\"fancy\"` parse as `Kind::SoFancy`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "Google")]
    Google,
    #[serde(rename = "Microsoft")]
    Microsoft,

}

impl ToString for Provider {
    fn to_string(&self) -> String {
        match self {
            Self::Google => String::from("Google"),
            Self::Microsoft => String::from("Microsoft"),
        }
    }
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Google
    }
}

