/*
 * spoke_handler
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemTime {
    #[serde(rename = "secs_since_epoch")]
    pub secs_since_epoch: i32,
    #[serde(rename = "nanos_since_epoch")]
    pub nanos_since_epoch: i32,
}

impl SystemTime {
    pub fn new(secs_since_epoch: i32, nanos_since_epoch: i32) -> SystemTime {
        SystemTime {
            secs_since_epoch,
            nanos_since_epoch,
        }
    }
}

