/**
 * spoke_handler
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateCalendarParams from './model/CreateCalendarParams';
import Event from './model/Event';
import EventStatus from './model/EventStatus';
import Provider from './model/Provider';
import SystemTime from './model/SystemTime';
import CalendarEventsApi from './api/CalendarEventsApi';
import CalendarsApi from './api/CalendarsApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SpokeHandler = require('index'); // See note below*.
* var xxxSvc = new SpokeHandler.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SpokeHandler.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SpokeHandler.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SpokeHandler.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.2.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateCalendarParams model constructor.
     * @property {module:model/CreateCalendarParams}
     */
    CreateCalendarParams,

    /**
     * The Event model constructor.
     * @property {module:model/Event}
     */
    Event,

    /**
     * The EventStatus model constructor.
     * @property {module:model/EventStatus}
     */
    EventStatus,

    /**
     * The Provider model constructor.
     * @property {module:model/Provider}
     */
    Provider,

    /**
     * The SystemTime model constructor.
     * @property {module:model/SystemTime}
     */
    SystemTime,

    /**
    * The CalendarEventsApi service constructor.
    * @property {module:api/CalendarEventsApi}
    */
    CalendarEventsApi,

    /**
    * The CalendarsApi service constructor.
    * @property {module:api/CalendarsApi}
    */
    CalendarsApi
};
