/**
 * spoke_handler
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Provider } from './provider';

export class CreateCalendarParams {
    'oauthClientId'?: string | null;
    'oauthClientSecret'?: string | null;
    'oauthRefreshToken': string;
    'platform': Provider;
    'calendarIdsToSync'?: Array<string> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "oauthClientId",
            "baseName": "oauth_client_id",
            "type": "string"
        },
        {
            "name": "oauthClientSecret",
            "baseName": "oauth_client_secret",
            "type": "string"
        },
        {
            "name": "oauthRefreshToken",
            "baseName": "oauth_refresh_token",
            "type": "string"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "Provider"
        },
        {
            "name": "calendarIdsToSync",
            "baseName": "calendar_ids_to_sync",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return CreateCalendarParams.attributeTypeMap;
    }
}

export namespace CreateCalendarParams {
}
