/**
 * spoke_handler
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SystemTime {
    'secsSinceEpoch': number;
    'nanosSinceEpoch': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "secsSinceEpoch",
            "baseName": "secs_since_epoch",
            "type": "number"
        },
        {
            "name": "nanosSinceEpoch",
            "baseName": "nanos_since_epoch",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SystemTime.attributeTypeMap;
    }
}

