# coding: utf-8

"""
    spoke_handler

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.provider import Provider
from typing import Optional, Set
from typing_extensions import Self

class CreateCalendarParams(BaseModel):
    """
    CreateCalendarParams
    """ # noqa: E501
    oauth_client_id: Optional[StrictStr] = None
    oauth_client_secret: Optional[StrictStr] = None
    oauth_refresh_token: StrictStr
    platform: Provider
    calendar_ids_to_sync: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["oauth_client_id", "oauth_client_secret", "oauth_refresh_token", "platform", "calendar_ids_to_sync"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateCalendarParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if oauth_client_id (nullable) is None
        # and model_fields_set contains the field
        if self.oauth_client_id is None and "oauth_client_id" in self.model_fields_set:
            _dict['oauth_client_id'] = None

        # set to None if oauth_client_secret (nullable) is None
        # and model_fields_set contains the field
        if self.oauth_client_secret is None and "oauth_client_secret" in self.model_fields_set:
            _dict['oauth_client_secret'] = None

        # set to None if calendar_ids_to_sync (nullable) is None
        # and model_fields_set contains the field
        if self.calendar_ids_to_sync is None and "calendar_ids_to_sync" in self.model_fields_set:
            _dict['calendar_ids_to_sync'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateCalendarParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "oauth_client_id": obj.get("oauth_client_id"),
            "oauth_client_secret": obj.get("oauth_client_secret"),
            "oauth_refresh_token": obj.get("oauth_refresh_token"),
            "platform": obj.get("platform"),
            "calendar_ids_to_sync": obj.get("calendar_ids_to_sync")
        })
        return _obj


