# coding: utf-8

"""
    spoke_handler

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.calendars_api import CalendarsApi


class TestCalendarsApi(unittest.TestCase):
    """CalendarsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarsApi()

    def tearDown(self) -> None:
        pass

    def test_calendar_calendars_create_calendar(self) -> None:
        """Test case for calendar_calendars_create_calendar

        """
        pass

    def test_calendar_calendars_delete_calendar(self) -> None:
        """Test case for calendar_calendars_delete_calendar

        """
        pass

    def test_calendar_calendars_get_calendar(self) -> None:
        """Test case for calendar_calendars_get_calendar

        """
        pass

    def test_calendar_calendars_list_calendars(self) -> None:
        """Test case for calendar_calendars_list_calendars

        """
        pass

    def test_calendar_calendars_update_calendar(self) -> None:
        """Test case for calendar_calendars_update_calendar

        """
        pass


if __name__ == '__main__':
    unittest.main()
