# coding: utf-8

"""
    spoke_handler

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.event import Event

class TestEvent(unittest.TestCase):
    """Event unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Event:
        """Test Event
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Event`
        """
        model = Event()
        if include_optional:
            return Event(
                id = 56,
                google_id = '',
                name = '',
                account_id = 56,
                meeting_url = '',
                start_time = openapi_client.models.system_time.SystemTime(
                    secs_since_epoch = 0.0, 
                    nanos_since_epoch = 0.0, ),
                calendar_id = 56,
                attendees = None,
                record = True,
                is_organizer = True,
                end_time = openapi_client.models.system_time.SystemTime(
                    secs_since_epoch = 0.0, 
                    nanos_since_epoch = 0.0, ),
                status = 'PrepareRecording',
                error = '',
                session_id = '',
                project_id = 56,
                refuse_recording_by = '',
                delete_token = '',
                recurring_event_id = '',
                is_recurring = True,
                agenda_id = 56,
                uuid = ''
            )
        else:
            return Event(
                id = 56,
                google_id = '',
                name = '',
                account_id = 56,
                meeting_url = '',
                start_time = openapi_client.models.system_time.SystemTime(
                    secs_since_epoch = 0.0, 
                    nanos_since_epoch = 0.0, ),
                calendar_id = 56,
                attendees = None,
                record = True,
                is_organizer = True,
                end_time = openapi_client.models.system_time.SystemTime(
                    secs_since_epoch = 0.0, 
                    nanos_since_epoch = 0.0, ),
                status = 'PrepareRecording',
                delete_token = '',
                is_recurring = True,
                uuid = '',
        )
        """

    def testEvent(self):
        """Test Event"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
