# coding: utf-8

"""
    spoke_handler

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.event_status import EventStatus

class TestEventStatus(unittest.TestCase):
    """EventStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventStatus(self):
        """Test EventStatus"""
        # inst = EventStatus()

if __name__ == '__main__':
    unittest.main()
