# coding: utf-8

"""
    spoke_handler

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.calendar_events_api import CalendarEventsApi


class TestCalendarEventsApi(unittest.TestCase):
    """CalendarEventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarEventsApi()

    def tearDown(self) -> None:
        pass

    def test_calendar_calendar_events_get_event(self) -> None:
        """Test case for calendar_calendar_events_get_event

        """
        pass

    def test_calendar_calendar_events_list_events(self) -> None:
        """Test case for calendar_calendar_events_list_events

        """
        pass

    def test_calendar_calendar_events_schedule_record_event(self) -> None:
        """Test case for calendar_calendar_events_schedule_record_event

        """
        pass

    def test_calendar_calendar_events_unschedule_record_event(self) -> None:
        """Test case for calendar_calendar_events_unschedule_record_event

        """
        pass


if __name__ == '__main__':
    unittest.main()
