# coding: utf-8

"""
    spoke_handler

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_calendar_params import CreateCalendarParams

class TestCreateCalendarParams(unittest.TestCase):
    """CreateCalendarParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCalendarParams:
        """Test CreateCalendarParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCalendarParams`
        """
        model = CreateCalendarParams()
        if include_optional:
            return CreateCalendarParams(
                oauth_client_id = '',
                oauth_client_secret = '',
                oauth_refresh_token = '',
                platform = 'Google',
                calendar_ids_to_sync = [
                    ''
                    ]
            )
        else:
            return CreateCalendarParams(
                oauth_refresh_token = '',
                platform = 'Google',
        )
        """

    def testCreateCalendarParams(self):
        """Test CreateCalendarParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
