/**
 * spoke_handler
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpokeHandler);
  }
}(this, function(expect, SpokeHandler) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SpokeHandler.CreateCalendarParams();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateCalendarParams', function() {
    it('should create an instance of CreateCalendarParams', function() {
      // uncomment below and update the code to test CreateCalendarParams
      //var instance = new SpokeHandler.CreateCalendarParams();
      //expect(instance).to.be.a(SpokeHandler.CreateCalendarParams);
    });

    it('should have the property oauthClientId (base name: "oauth_client_id")', function() {
      // uncomment below and update the code to test the property oauthClientId
      //var instance = new SpokeHandler.CreateCalendarParams();
      //expect(instance).to.be();
    });

    it('should have the property oauthClientSecret (base name: "oauth_client_secret")', function() {
      // uncomment below and update the code to test the property oauthClientSecret
      //var instance = new SpokeHandler.CreateCalendarParams();
      //expect(instance).to.be();
    });

    it('should have the property oauthRefreshToken (base name: "oauth_refresh_token")', function() {
      // uncomment below and update the code to test the property oauthRefreshToken
      //var instance = new SpokeHandler.CreateCalendarParams();
      //expect(instance).to.be();
    });

    it('should have the property platform (base name: "platform")', function() {
      // uncomment below and update the code to test the property platform
      //var instance = new SpokeHandler.CreateCalendarParams();
      //expect(instance).to.be();
    });

    it('should have the property calendarIdsToSync (base name: "calendar_ids_to_sync")', function() {
      // uncomment below and update the code to test the property calendarIdsToSync
      //var instance = new SpokeHandler.CreateCalendarParams();
      //expect(instance).to.be();
    });

  });

}));
