/**
 * spoke_handler
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Provider from './Provider';

/**
 * The CreateCalendarParams model module.
 * @module model/CreateCalendarParams
 * @version 0.2.0
 */
class CreateCalendarParams {
    /**
     * Constructs a new <code>CreateCalendarParams</code>.
     * @alias module:model/CreateCalendarParams
     * @param oauthRefreshToken {String} 
     * @param platform {module:model/Provider} 
     */
    constructor(oauthRefreshToken, platform) { 
        
        CreateCalendarParams.initialize(this, oauthRefreshToken, platform);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, oauthRefreshToken, platform) { 
        obj['oauth_refresh_token'] = oauthRefreshToken;
        obj['platform'] = platform;
    }

    /**
     * Constructs a <code>CreateCalendarParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateCalendarParams} obj Optional instance to populate.
     * @return {module:model/CreateCalendarParams} The populated <code>CreateCalendarParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateCalendarParams();

            if (data.hasOwnProperty('oauth_client_id')) {
                obj['oauth_client_id'] = ApiClient.convertToType(data['oauth_client_id'], 'String');
            }
            if (data.hasOwnProperty('oauth_client_secret')) {
                obj['oauth_client_secret'] = ApiClient.convertToType(data['oauth_client_secret'], 'String');
            }
            if (data.hasOwnProperty('oauth_refresh_token')) {
                obj['oauth_refresh_token'] = ApiClient.convertToType(data['oauth_refresh_token'], 'String');
            }
            if (data.hasOwnProperty('platform')) {
                obj['platform'] = Provider.constructFromObject(data['platform']);
            }
            if (data.hasOwnProperty('calendar_ids_to_sync')) {
                obj['calendar_ids_to_sync'] = ApiClient.convertToType(data['calendar_ids_to_sync'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateCalendarParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateCalendarParams</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateCalendarParams.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['oauth_client_id'] && !(typeof data['oauth_client_id'] === 'string' || data['oauth_client_id'] instanceof String)) {
            throw new Error("Expected the field `oauth_client_id` to be a primitive type in the JSON string but got " + data['oauth_client_id']);
        }
        // ensure the json data is a string
        if (data['oauth_client_secret'] && !(typeof data['oauth_client_secret'] === 'string' || data['oauth_client_secret'] instanceof String)) {
            throw new Error("Expected the field `oauth_client_secret` to be a primitive type in the JSON string but got " + data['oauth_client_secret']);
        }
        // ensure the json data is a string
        if (data['oauth_refresh_token'] && !(typeof data['oauth_refresh_token'] === 'string' || data['oauth_refresh_token'] instanceof String)) {
            throw new Error("Expected the field `oauth_refresh_token` to be a primitive type in the JSON string but got " + data['oauth_refresh_token']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['calendar_ids_to_sync'])) {
            throw new Error("Expected the field `calendar_ids_to_sync` to be an array in the JSON data but got " + data['calendar_ids_to_sync']);
        }

        return true;
    }


}

CreateCalendarParams.RequiredProperties = ["oauth_refresh_token", "platform"];

/**
 * @member {String} oauth_client_id
 */
CreateCalendarParams.prototype['oauth_client_id'] = undefined;

/**
 * @member {String} oauth_client_secret
 */
CreateCalendarParams.prototype['oauth_client_secret'] = undefined;

/**
 * @member {String} oauth_refresh_token
 */
CreateCalendarParams.prototype['oauth_refresh_token'] = undefined;

/**
 * @member {module:model/Provider} platform
 */
CreateCalendarParams.prototype['platform'] = undefined;

/**
 * @member {Array.<String>} calendar_ids_to_sync
 */
CreateCalendarParams.prototype['calendar_ids_to_sync'] = undefined;






export default CreateCalendarParams;

