/**
 * spoke_handler
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class EventStatus.
* @enum {}
* @readonly
*/
export default class EventStatus {
    
        /**
         * value: "PrepareRecording"
         * @const
         */
        "PrepareRecording" = "PrepareRecording";

    
        /**
         * value: "Recording"
         * @const
         */
        "Recording" = "Recording";

    
        /**
         * value: "Error"
         * @const
         */
        "Error" = "Error";

    
        /**
         * value: "None"
         * @const
         */
        "None" = "None";

    

    /**
    * Returns a <code>EventStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/EventStatus} The enum <code>EventStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

